support space in workspace
rapidsai/cuxfilter pull request #267
Opened 2021-04-14 20:05 UTC by jolorunyomi

# Summary
This PR adds support for spaces in workspace

2021-04-14 20:06 UTC, jolorunyomi commented on ci/docs/build.sh
> +    rm -rf "$DOCS_WORKSPACE/api/"$PROJECT/$BRANCH_VERSION/*
```suggestion
    rm -rf "$DOCS_WORKSPACE/api/$PROJECT/$BRANCH_VERSION/*	
```

2021-04-14 20:07 UTC, jolorunyomi commented on ci/docs/build.sh
> +mv $PROJECT_WORKSPACE/docs/_build/html/* "$DOCS_WORKSPACE/api/cuxfilter/"$BRANCH_VERSION
```suggestion
mv $PROJECT_WORKSPACE/docs/_build/html/* "$DOCS_WORKSPACE/api/cuxfilter/$BRANCH_VERSION
```

2021-04-14 20:38 UTC, ajschmidt8 requested changes

2021-04-14 20:38 UTC, ajschmidt8 commented on ci/docs/build.sh
> +    rm -rf "$DOCS_WORKSPACE/api/$PROJECT/$BRANCH_VERSION/*
```suggestion
    rm -rf "$DOCS_WORKSPACE/api/$PROJECT/$BRANCH_VERSION/"*	
```
looks like this is missing a closing `"`

2021-04-14 20:38 UTC, ajschmidt8 commented on ci/docs/build.sh
> +mv $PROJECT_WORKSPACE/docs/_build/html/* "$DOCS_WORKSPACE/api/cuxfilter/$BRANCH_VERSION
```suggestion
mv $PROJECT_WORKSPACE/docs/_build/html/* "$DOCS_WORKSPACE/api/cuxfilter/$BRANCH_VERSION"
```

looks like this is missing a closing `"`

2021-05-25 14:19 UTC, ajschmidt8 requested changes

2021-05-25 14:19 UTC, ajschmidt8 commented on ci/docs/build.sh
> +    rm -rf "$DOCS_WORKSPACE/api/$PROJECT/$BRANCH_VERSION/*
@jolorunyomi, I still don't see a closing `"` here.

2021-05-25 14:19 UTC, ajschmidt8 commented on ci/docs/build.sh
> +mv $PROJECT_WORKSPACE/docs/_build/html/* "$DOCS_WORKSPACE/api/cuxfilter/$BRANCH_VERSION
@jolorunyomi, I still don't see a closing `"` here.

2021-05-31 14:33 UTC, jolorunyomi commented on ci/docs/build.sh
> +mv $PROJECT_WORKSPACE/docs/_build/html/* "$DOCS_WORKSPACE/api/cuxfilter/$BRANCH_VERSION
```suggestion
mv $PROJECT_WORKSPACE/docs/_build/html/* "$DOCS_WORKSPACE/api/cuxfilter/$BRANCH_VERSION"
```

2021-05-31 14:34 UTC, jolorunyomi commented on ci/docs/build.sh
> +mv $PROJECT_WORKSPACE/docs/_build/html/* "$DOCS_WORKSPACE/api/cuxfilter/$BRANCH_VERSION"
```suggestion
mv "$PROJECT_WORKSPACE/docs/_build/html/"* "$DOCS_WORKSPACE/api/cuxfilter/$BRANCH_VERSION"
```

2021-06-01 16:21 UTC, ajschmidt8 approved these changes

2021-06-01 16:22 UTC, ajschmidt8 commented
@gpucibot merge

2021-06-01 16:22 UTC, merged