Require Numba 0.57.0+ & NumPy 1.21.0+
rapidsai/cuxfilter pull request #480
Opened 2023-05-30 22:51 UTC by jakirkham

Align with the rest of RAPIDS on these requirements. Also needed for CUDA 12 support.

2023-05-30 23:01 UTC, jakirkham commented
Could someone please add the "improvement" & "non-breaking" labels?

2023-05-30 23:15 UTC, bdice commented on conda/recipes/cuxfilter/meta.yaml
> +    - numba >=1.21
```suggestion
    - numpy >=1.21
```

2023-05-30 23:26 UTC, jakirkham commented on conda/recipes/cuxfilter/meta.yaml
> +    - numba >=1.21
Oops 🤦‍♂️

Should now be fixed 😅

2023-05-31 00:02 UTC, AjayThorve commented
The docs build is failing, due to an issue where numpy v1.24.3 prevent holoviews to render cuxfilter docs charts, should be fixed in #479 [here](https://github.com/AjayThorve/cuxfilter/blob/fix/failing-tests/dependencies.yaml#L76)

2023-05-31 00:36 UTC, bdice commented
> The docs build is failing, due to an issue where numpy v1.24.3 prevent holoviews to render cuxfilter docs charts

@AjayThorve Is there an upstream bug in holoviews / numpy that we can link to here so that we know when this limitation is lifted? This is important to track for all of RAPIDS, because cuxfilter is installed by default in the `rapids` metapackage and users may have environment conflicts that require NumPy 1.24. We've seen NumPy 1.24 compatibility requests for cudf and were able to lift this upper bound.

2023-05-31 00:45 UTC, AjayThorve commented
> @AjayThorve Is there an upstream bug in holoviews / numpy that we can link to in that PR so that we know when this limitation is lifted? This is important to track for all of RAPIDS, because `cuxfilter` is installed by default in the `rapids` metapackage and users may have environment conflicts that require NumPy 1.24. We've seen NumPy 1.24 compatibility requests for cudf and were able to lift this upper bound.

Hey @bdice, so this issue is already fixed in datashader (https://github.com/holoviz/datashader/pull/1176), although it's not yet part of any release(the latest released datashader version is 0.14.4, and this PR is part of the 0.14.5 milestone). How do you suggest we proceed in this scenario?

2023-05-31 01:05 UTC, jakirkham commented
Can we raise an issue on their repo requesting a release (and link that issue here)?

2023-05-31 01:13 UTC, AjayThorve commented
Have asked for an ETA for release here (https://discourse.holoviz.org/t/module-numpy-has-no-attribute-warnings/5402)

2023-05-31 07:12 UTC, Hoxbro commented
We have released datashader 1.15, and are working on adding it to conda-forge [here](https://github.com/conda-forge/datashader-feedstock/pull/28). So hopefully you will soon be unblocked.

2023-05-31 09:13 UTC, ianthomas23 commented
Conda-forge datashader-feedstock v0.15.0 PR has been merged so you should be able to proceed shortly.

2023-05-31 10:01 UTC, jakirkham commented
Thank you both! 🙏

2023-05-31 13:24 UTC, raydouglass approved these changes

2023-05-31 16:19 UTC, AjayThorve commented
thanks everyone, #479 should fix the CI issues, and this PR should be good to merge after that

2023-05-31 16:37 UTC, AjayThorve commented
@jakirkham can you merge/rebase with `main`, that should fix the CI failures

2023-05-31 16:38 UTC, AjayThorve approved these changes

2023-05-31 16:45 UTC, jakirkham commented
Toggling for CI

2023-05-31 16:56 UTC, AjayThorve approved these changes

2023-05-31 16:56 UTC, bdice requested changes
Please update `dependencies.yaml` to align. We need `numpy` and `numba` pinnings in the `run` section: https://github.com/rapidsai/cuxfilter/blob/472f839e5eb9864dbc772e414b6759d62505f2e8/dependencies.yaml#L107-L128

2023-05-31 16:56 UTC, AjayThorve commented
/merge

2023-05-31 16:58 UTC, raydouglass approved these changes

2023-05-31 18:43 UTC, AjayThorve commented
> Please update `dependencies.yaml` to align. We need `numpy` and `numba` pinnings and to make the `run` section align with the conda list of run dependencies:

@bdice, I pushed the requested changes

2023-05-31 19:08 UTC, AjayThorve commented
/merge

2023-05-31 19:08 UTC, merged

2023-05-31 19:27 UTC, jakirkham commented
Thanks all! 🙏