Build and test with CUDA 12.5.1
rapidsai/cuxfilter pull request #607
Opened 2024-07-11 20:12 UTC by KyleFromNVIDIA

This PR updates the latest CUDA build/test version 12.2.2 to 12.5.1.

2024-07-16 17:23 UTC, jameslamb requested changes
I think this should be updated to 12.5:

https://github.com/rapidsai/cuxfilter/blob/14237a1a911fd0ef48555db63c8f4b7b4f533cdc/docs/source/user_guide/installation.rst#L10-L12

(context: https://github.com/rapidsai/dask-cuda/pull/1357#pullrequestreview-2180844366)

----

This one is wrong (and looks like it has been since before this PR):

https://github.com/rapidsai/cuxfilter/blob/14237a1a911fd0ef48555db63c8f4b7b4f533cdc/docs/source/user_guide/installation.rst#L35-L42

It's has a comment that says "for CUDA 11.8", but then pulls a CUDA 12.0 image, and then the `docker run` after that `docker pull` is for an 11.8 image.

The `rapidsai/rapidsai` image isn't updated any more. Context: https://github.com/rapidsai/deployment/issues/382

Since that doc is encouraging looking at a notebook at `localhost:8888`, it should probably be using this image in both commands

```text
rapidsai/notebooks:24.06-cuda12.0-py3.10
```

(ref: https://hub.docker.com/r/rapidsai/notebooks/tags)

I just posted a separate question (does not need to block this PR) about updating those images at https://github.com/rapidsai/build-planning/issues/73.

2024-07-17 17:49 UTC, jameslamb approved these changes

2024-07-17 17:52 UTC, jakirkham approved these changes

2024-07-17 17:52 UTC, jakirkham commented
/merge

2024-07-17 18:27 UTC, merged

2024-07-17 18:30 UTC, jakirkham commented
Thanks all! 🙏